language: python
  
python: "3.6"

git:
  depth: 1

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py makemigrations vaccine
  - python manage.py makemigrations users
  - python manage.py migrate vaccine
  - python manage.py migrate users

test:
  adapter: postgresql
  database: travis_ci_test
  
install:
  - pip install -r requirements.txt
  - pip install codecov
  
script:
  - coverage run manage.py test users/tests vaccine/tests pages/tests

notifications:
  slack: vacseen:7ogtQG6Nde9OFbafzV41HWHd

after_success:
  - codecov
  