language: python
  
python: "3.6"

git:
  depth: 1
  
install:
  - pip install -r requirements.txt
  
script:
  - coverage run manage.py test users/tests

notifications:
  slack: vacseen:7ogtQG6Nde9OFbafzV41HWHd
  